name: CD

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.set_version.outputs.new_version }}
    env:
      YARN_OPTION: --patch
    steps:
      - uses: actions/checkout@v2

      - name: Set yarn option
        if: |
          contains(github.event.pull_request.labels.*.name, 'enhancement')
        run: |
          env 'YARN_OPTION=--minor' >> $GITHUB_ENV

      - name: Bump version
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: version --no-git-tag-version ${{ env.YARN_OPTION }}

      - name: Set new version environment
        id: set_version
        run: |
          version=$(jq -r '.version' package.json)
          echo "::set-output name=new_version::${version}"

      - name: Push version
        uses: EndBug/add-and-commit@v9
        id: push
        with:
          default_author: github_actions
          message: 'Application update to ${{ steps.set_version.outputs.new_version }}'

      - name: Push version to develop
        run: |
          git checkout develop
          git cherry-pick  ${{ steps.push.outputs.commit_sha }}
          git push origin develop

  notify-deploy-succeeded:
    name: Notify to Slack
    runs-on: ubuntu-latest
    needs:
      - versioning
    steps:
      - name: echo version
        run: |
          echo The new version is ${{ needs.versioning.outputs.new_version }}
